### ISSUE TITLE
Support Proxy configuration

### ISSUE THREAD

**Issue by djKianoosh** [4finance/uptodate-gradle-plugin#18]
In your httpBuilder after line 46, 
https://github.com/4finance/uptodate-gradle-plugin/blob/master/src/main/groovy/com/ofg/uptodate/finder/MavenNewVersionFinder.groovy#L46
could you please add a line line they have commented out in this gist:
https://gist.github.com/sarmbruster/8114445
to support using a proxy connection? 
http://groovy.codehaus.org/modules/http-builder/apidocs/groovyx/net/http/HTTPBuilder.html#setProxy%28java.lang.String,%20int,%20java.lang.String%29
Something like:
```httpBuilder.setProxy( proxyHostFromSystem, proxyPortFromSystem, "http" )```

Alternatively, you could let that be configurable. Up to you really. One way or another. As it is, I get a connection timed out behind a corporate proxy. 

```
Caused by: java.util.concurrent.ExecutionException: org.apache.http.conn.ConnectTimeoutException: Connect to search.maven.org/207.223.241.72:80 timed out
        at java_util_concurrent_Future$get.call(Unknown Source)
        at com.ofg.uptodate.finder.MavenNewVersionFinder$_findNewerInMavenCentralRepo_closure3.doCall(MavenNewVersionFinder.groovy:48)
        at com.ofg.uptodate.finder.MavenNewVersionFinder.findNewerInMavenCentralRepo(MavenNewVersionFinder.groovy:48)
        at com.ofg.uptodate.finder.MavenNewVersionFinder.this$2$findNewerInMavenCentralRepo(MavenNewVersionFinder.groovy)
        at com.ofg.uptodate.finder.MavenNewVersionFinder$this$2$findNewerInMavenCentralRepo.callCurrent(Unknown Source)
        at com.ofg.uptodate.finder.MavenNewVersionFinder.findNewer(MavenNewVersionFinder.groovy:39)
        at com.ofg.uptodate.finder.NewVersionFinder$findNewer.call(Unknown Source)
        at com.ofg.uptodate.finder.NewVersionFinderInAllRepositories$_findNewer_closure1.doCall(NewVersionFinderInAllRepositories.groovy:23)
        at com.ofg.uptodate.finder.NewVersionFinderInAllRepositories.findNewer(NewVersionFinderInAllRepositories.groovy:22)
        at com.ofg.uptodate.finder.NewVersionFinderInAllRepositories$findNewer.call(Unknown Source)
        at com.ofg.uptodate.UptodatePlugin$_apply_closure1.doCall(UptodatePlugin.groovy:37)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 44 more
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to search.maven.org/207.223.241.72:80 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:129)
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:183)
        at org.apache.http.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:151)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1066)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.AsyncHTTPBuilder.doRequestSuper(AsyncHTTPBuilder.java:146)
        at groovyx.net.http.AsyncHTTPBuilder.access$000(AsyncHTTPBuilder.java:59)
        at groovyx.net.http.AsyncHTTPBuilder$1.call(AsyncHTTPBuilder.java:131)
```

**Comment by RobWin** [comment]
+1.
Same issue here.

**Comment by marcingrzejszczak** [comment]
We're on it :) Will try to fix that ASAP

**Comment by RobWin** [comment]
Great. Thx

**Comment by marcingrzejszczak** [comment]
Check out version 1.2.0 it should support proxying and let us know :) Kudos to @cbuleandra !

**Comment by marcingrzejszczak** [comment]
@RobWin @djKianoosh - please check https://github.com/4finance/uptodate-gradle-plugin#how-to-run-the-plugin-if-you-are-behind-an-http-proxy for info on how to configure the proxy.

**Comment by djKianoosh** [comment]
Works great. Good work!

**Comment by RobWin** [comment]
Thx. 
One enhancement idea.

In gradle I configure proxy settings as System Properties. Fpr example.

```
systemProp.https.proxyHost=192.168.1.112
systemProp.https.proxyPort=3000
systemProp.https.nonProxyHosts=localhost|127.0.0.1
systemProp.http.proxyHost=192.168.1.112
systemProp.http.proxyPort=3000
systemProp.http.nonProxyHosts=localhost|127.0.0.1
```
The plugin could automatically check, if the http proxy System Properties are set.

Kind regards,

Robert

**Comment by marcingrzejszczak** [comment]
Hi Robert!

can you file a separate issue for that?

For now you can use the uptodate closure to set that:

```
uptodate {
    proxyHostname systemProp.https.proxyHost
    proxyPort systemProp.https.proxyPort
    proxyScheme 'http'
}
```

if you set it like above - does it work for you?

**Comment by djKianoosh** [comment]
I had to do it like this:
```
uptodate {
    proxyHostname System.properties['https.proxyHost']
    proxyPort System.properties['https.proxyPort'] as int
    proxyScheme 'http'
}
```

**Comment by RobWin** [comment]
Yes it works like this for me.

```
proxyHostname System.properties['http.proxyHost']
proxyPort System.properties['http.proxyPort'].toInteger()
```

**Comment by cbuleandra** [comment]
Hello,

I've created an issue to add support for proxy settings configuration via System properties, https://github.com/4finance/uptodate-gradle-plugin/issues/20. We'll start working on it as soon as possible.

Regards,
Catalin

**Comment by marcingrzejszczak** [comment]
System props done  in version `1.3.0` - kudos to @cbuleandra and enjoy :)
