### ISSUE TITLE
BUILD failed during uptodate: No such property: versioning for class: org.apache.http.conn.EofSensorInputStream

### ISSUE THREAD

**Issue by kkrzeminski** [4finance/uptodate-gradle-plugin#47]
gradlew uptodate

    paused by: groovy.lang.MissingPropertyException: No such property: versioning for class: org.apache.http.conn.EofSensorInputStream
           at com.ofg.uptodate.finder.jcenter.JCenterNewVersionFinderFactory$_closure1_closure4.doCall(JCenterNewVersionFinderFactory.groovy:57)
           at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
           at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
           at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
           at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
           at groovyx.net.http.AsyncHTTPBuilder.doRequestSuper(AsyncHTTPBuilder.java:146)
           at groovyx.net.http.AsyncHTTPBuilder.access$000(AsyncHTTPBuilder.java:59)
           at groovyx.net.http.AsyncHTTPBuilder$1.call(AsyncHTTPBuilder.java:131)

**Comment by szpak** [comment]
It is issue #42. Do you use uptodate-gradle-plugin 1.5.1?

**Comment by kkrzeminski** [comment]
Sorry. Now everything works ok.
