### ISSUE TITLE
Remove deprecation stacktrace on Gradle 3.2

### ISSUE THREAD

**Issue by szpak** [4finance/uptodate-gradle-plugin#62]
`<<` has been deprecated in Gradle 3.x and a nasty stack trace is print in the projects using this plugin.

```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at org.gradle.api.internal.AbstractTask.leftShift(AbstractTask.java:505)
        at org.gradle.api.Task$leftShift.call(Unknown Source)
        at com.ofg.uptodate.UptodatePlugin.apply(UptodatePlugin.groovy:36)
        at com.ofg.uptodate.UptodatePlugin.apply(UptodatePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
(...)
```

Offensive [line](https://github.com/4finance/uptodate-gradle-plugin/blob/95671cbc3458a3167527d5e00fa888594558b441/src/main/groovy/com/ofg/uptodate/UptodatePlugin.groovy#L36).

**Comment by szpak** [comment]
Fixed in master. Waiting for a release.
